 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  causalvidqa: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /home/shreyasjena/BTP/SeViLA/data/annotations/mixtral/train.json
          storage: /home/shreyasjena/BTP/SeViLA/data/annotations/mixtral/train.json
        val:
          url: /home/shreyasjena/BTP/SeViLA/data/annotations/mixtral/val.json
          storage: /home/shreyasjena/BTP/SeViLA/data/annotations/mixtral/val.json
        test:
          url: /home/shreyasjena/BTP/SeViLA/data/annotations/mixtral/orig_sample.json
          storage: /home/shreyasjena/BTP/SeViLA/data/annotations/mixtral/orig_sample.json
      videos:
        storage: /home/shreyasjena/BTP/SeViLA/data/videos
